import pytest
import grpc
# generated by proto compiler
import helloworld_pb2
import helloworld_pb2_grpc
# my server implemets gRPC methods
from greeter_server import Greeter

stub = helloworld_pb2_grpc.GreeterStub(grpc.insecure_channel('localhost:50051'))
NAMES = ["Eduardo", "Maria", "Jose"]

@pytest.fixture(params=NAMES)
def names(request):
    return request.param


def test_hw_sayhello(names):
    """
        Test GreeterServicer SayHello method 
    """
    print("---> %s" % names)
    response = stub.SayHello(helloworld_pb2.HelloRequest(name=names))
    print("Greeter client received: " + response.message)


def test_hw_ola():
    """
        Test GreeterServicer Ola method
    """
    response = stub.Ola(helloworld_pb2.HelloRequest(name="John"))
    print("Greeter client received: " + response.message)
    


